### ISSUE TITLE
Spellcheck the docs

### ISSUE THREAD

**Issue by 05dirnbe** [tastyminerals/NEFI2#2]
Hi,

if you search for the string "**throuregh**" in the doc, you will find it somewhere in the installation guide. The fact that is obviously misspelled indicates that the docs are in need of being swept by a spellchecker.

Please always run a spellchecker while writing text.

best, m

**Comment by tastyminerals** [comment]
I am aware of the typos in the docs. Didn't check them completely though.

**Comment by Rapdrei** [comment]
Hi Michael, we will expand and check our doc as soon as we are finished with the coding.
