### ISSUE TITLE
Mac installation guide

### ISSUE THREAD

**Issue by 05dirnbe** [tastyminerals/NEFI2#3]
Hi,

here is how i managed to install most of the dependecies on mac. Take the test, write it out and spellcheck it properly and put it in the docs as a guide for mac users. **Do not forget to add the part about thinning which i havent treated as of yet**! 

Get homebrew, a powerful package manger for mac os, by running:
`cd ~`
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
`brew update`

 If you dont have it already install python 3 like so:
`$ brew install python3`
`$ brew linkapps` 

Next we update our `PATH`  in `~/.bash_profile` to indicate that Homebrew packages should be used before any system packages. SImply add the following line to `~/.bash_profile`:

`export PATH=/usr/local/bin:$PATH`

Next reload the contents of `~/.bash_profile`:
`source ~/.bash_profile`

After typing:

`which python3`

you should see:

`/usr/local/bin/python`

Now we can install the actual dependencies by using `brew` and `pip3`:

`pip3 install numpy`
`pip3 install networkx`
`pip3 install demjson`
`pip3 install PyQt5`

Some of these packages rely on a compiler being present. If you don't have we highly recommend to get the current version of clang.

Finally, we install `opencv 3` with the necessary python bindings. To do so we execute:

`brew install opencv3 --with-python3`

At this point I recommend to start a `python3` interpreter and to test whether the import statements go through. 

```
Python 3.5.1 (default, Jan 22 2016, 08:52:08) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> import numpy
>>> import demjson
>>> import PyQt5
>>> import cv2
>>> 
```
Ideally, all imports go through and you are ready to start NEFI2. 

At the time of testing this, however, it seemed that importing opencv3 faild, with the interpreter claiming that it doesn't know the module. Upon closer inspection it was found that the necessary files where there, but a link between the opencv stuff and the python3 site-packages was missing. I expect this issue to be resolved soon by the developers of brew and opencv. In the meantime, it is possible to rectify the situation manually as follows.

Brew has palced `opencv3` somewhere in the its "cellar" which on my system resides here:

`/usr/local/Cellar/opencv3`

Somewhere below this path there is a `.so` file that we need to `symlink` to the `site-packages` folder of our python 3. On my system this file was found to be here:

`/usr/local/Cellar/opencv3/3.1.0_1/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so`

In the site-packes directory of my python 3 a corresponding `cv2.so` files was missing. You can find this directory by running:

`brew info python3`

All that is left to be done is to `symlink` the well-hidden, and strangely named, `cv2.cpython-35m-darwin.so` to its proper place amongst the site-packages. On my system it was done as follows:

`ln -s /usr/local/Cellar/opencv3/3.1.0_1/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so /usr/local/lib/python3.5/site-packages/cv2.so`

If the paths differ on your system you need to change the command accordingly. If done correctly the last import should succeed and you are good to go.

**Comment by tastyminerals** [comment]
Thanks, I shall add this to the docs!

**Comment by Rapdrei** [comment]
We may be able to create one package for the complete installation process using pydeploy. Phillipp is currently working on it. Unfortunatly to build this package with pydeploy one needs to read a huge riverbank documentation.
If we can set it up, we will need you to compile the resources for the mac package.

**Comment by 05dirnbe** [comment]
Dont worry about packaging the installation for mac. I think we can expect that a user is willing to simple brew the installation step by step. I definitely prefer installing this way, because if something fails due to changes somewhere, it is easier to deal with. Things will fail sooner or later.

**Comment by Rapdrei** [comment]
Ok then we try to make a python weel for thinning. If we upload it to the python wheel project, you should be able to install it with brew. But that's just a assumption. Unfortunatly we have no mac to test this.

**Comment by 05dirnbe** [comment]
I will open a new issue for this.
