### ISSUE TITLE
make pip3 install thinning work

### ISSUE THREAD

**Issue by 05dirnbe** [tastyminerals/NEFI2#4]
For nefi1 and python2.7 you could download and install the thinning module simply by typing:

`pip install thinning`

For python3 and pip3 id expect:

`pip3 install thinning`

Thus, you need to package the thinning code of nefi2 in the same way the code of nefi1 was packaged. Do not forget to credit also the original contributor Adrian. Also it needs to be uploaded somewhere where `pip3` is looking for it. This should be way easier than brew.

**Comment by tastyminerals** [comment]
It exists on PyPi under the name **thinning_py3**, unfortunately ``pip3 install thinning_py3`` crashes.

**Comment by 05dirnbe** [comment]
`git clone https://github.com/tastyminerals/thinning_py3.git`
`cd thinning_py3`
`sudo python3 setup.py install`

successfully added the thinning module to my `python3` packages. Compiler spat out some warnings though. I will soon test whether the module works.

Also, since the manual installation with `setup.py` works, it appears strange that the `pip3` installation crashes. Probably there's only some minor issue/missspecification that makes `pip3` break.
