### ISSUE TITLE
ImportError: No module named 'zope'

### ISSUE THREAD

**Issue by 05dirnbe** [tastyminerals/NEFI2#5]
It seems an additional module named `zope` is required to run NEFI2.

I tried to grab the module using `pip3` but it knows a bazillion modules that have something todo with `zope` so i could decide which one i needed. 

Please add the proper `pip3` command to the docs and tell me what to do!

cheers, m

**Comment by tastyminerals** [comment]
`sudo pip3 install zope.interface`
Yes, this is a new dependency.

**Comment by 05dirnbe** [comment]
... as is `zope.event` as it appears. I installed it using

`sudo pip3 install zope.event`

I hope this was correct.

**Comment by 05dirnbe** [comment]
... futhermore i added `qdarkstyle` like so

`pip3 install qdarkstyle`

**Comment by tastyminerals** [comment]
Yes, it is probably `zope.event` although on my system `zope.interface` is installed. 
Yes, `qdarkstyle` as well...

**Comment by 05dirnbe** [comment]
... and then i see a darkstyle (almost a johnny cash quote)! IT WORKS. YEAH baby YEAH. Gonna try it later.

**Comment by Rapdrei** [comment]
Hey Michael, we will include qdarkstyle and zope.event in the final installer packages :)
